name: Go Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tip:
    runs-on: ubuntu-latest
    container: aleksi/golang-tip:master
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download dependencies
        run: go mod download -x

      - name: Test
        run: go test -v ./...
